subprojects {
    apply plugin: 'java'

    group = 'de.a12.studio'
    version = '1.0-SNAPSHOT'

    tasks.withType(JavaCompile).configureEach {
        options.release = 21
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation 'org.jspecify:jspecify:1.0.0'
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}
