rootProject.name = 'a12-studio'

include 'a12-studio-commons'
include 'a12-studio-ui'
include 'a12-studio-server'
include 'a12-studio-models'
include 'a12-studio-models-validation'
include 'a12-studio-data-services'
include 'a12-studio-plugins:create-from-access'
include 'a12-studio-plugins:create-from-excel'
include 'a12-studio-plugins:application-groups'
include 'a12-studio-plugins:project-packager'
include 'a12-studio-plugin-manager'
