package de.a12.studio.ui.editors.documentmodel;

import de.a12.studio.models.documentmodel.Element;
import de.a12.studio.models.documentmodel.RuleConfig;
import de.a12.studio.models.documentmodel.RuleElement;
import de.a12.studio.modelsvalidation.ElementProperty;
import de.a12.studio.modelsvalidation.Severity;
import de.a12.studio.ui.editors.AbstractPropertyEditor;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;
import org.jspecify.annotations.NonNull;

import java.net.URL;
import java.util.Arrays;
import java.util.ResourceBundle;

/**
 * Edits a {@link RuleElement}'s {@link RuleConfig#getErrorCode()} (shown read-only - auto-generated by {@link
 * DocumentModelElementFactory#newRuleElement}, no evidence SME lets users hand-author it) and {@link
 * RuleConfig#getSeverity()}. The rest of {@link RuleConfig} ({@code errorEntityRelPath}, {@code errorCondition},
 * {@code errorMessage}) is edited by sibling panels included alongside this one (see
 * {@code document-model-validation-rule-editor.fxml}): {@link TargetFieldPanelController#configureRuleErrorEntity()},
 * a plain {@link de.a12.studio.ui.editors.propertyeditors.RichtextEditorController}, and {@link
 * de.a12.studio.ui.editors.propertyeditors.LocalizedTextPanelController#configureRuleErrorMessage()}.
 */
public class RulePropertiesPanelController extends AbstractPropertyEditor implements Initializable {

  @FXML
  private TextField errorCodeField;

  @FXML
  private ComboBox<String> severityComboBox;

  @Override
  public void initialize(URL location, ResourceBundle resources) {
    super.initialize(location, resources);
    severityComboBox.getItems().setAll(Arrays.stream(Severity.values()).map(Enum::name).toList());
    bindComboBox(severityComboBox, (el, value) -> getRule(el).setSeverity(value));
  }

  @Override
  public void setElement(@NonNull Element element) {
    super.setElement(element);
    setFieldValue(errorCodeField, getRule(element).getErrorCode());
    setFieldValue(severityComboBox, getRule(element).getSeverity());
  }

  @Override
  protected String validationProperty() {
    return ElementProperty.RULE_PROPERTIES;
  }

  private static RuleConfig getRule(Element element) {
    return ((RuleElement) element).getRule();
  }
}
