package de.a12.studio.ui.editors.overviewmodel.dialogs;

import de.a12.studio.models.overviewmodel.FilterSection;
import de.a12.studio.models.projects.ProjectItem;
import de.a12.studio.modelsvalidation.validators.ElementIndex;
import de.a12.studio.ui.Studio;
import de.a12.studio.ui.components.DialogController;
import de.a12.studio.ui.editors.PropertyEditorSaveMode;
import de.a12.studio.ui.editors.overviewmodel.FieldReferencesPanelController;
import de.a12.studio.ui.editors.propertyeditors.LocalizedTextPanelController;
import de.a12.studio.ui.events.StudioEventManager;
import javafx.fxml.FXML;
import javafx.scene.control.ButtonType;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import org.jspecify.annotations.NonNull;

import java.util.Optional;

/**
 * Add/edit dialog for a single {@link FilterSection}, opened from {@link
 * de.a12.studio.ui.editors.overviewmodel.OverviewSectionDataPanelController} by clicking a row or its Edit
 * button, or by the Add button. Edits the real, already-attached {@link FilterSection} live (there's no "add"
 * mode of its own - {@code Dialogs#showSectionForAdd} attaches a new, empty section before opening this
 * dialog), so a {@link FilterSectionSnapshot} taken before showing the dialog can undo those edits on Cancel,
 * mirroring {@link FilterGroupDialogController}. Section ID is auto-generated (see {@code Dialogs#shortId})
 * and shown read-only, matching SME's own section-data detail screen, whose id field is generated by a
 * middleware and never user-editable.
 */
public class SectionDataDialogController implements DialogController {

  @FXML
  private TextField idField;

  @FXML
  private LocalizedTextPanelController labelController;

  @FXML
  private FieldReferencesPanelController fieldsController;

  // Shared by the embedded label/fields panels so their commits aren't persisted while this dialog is open:
  // this dialog persists everything itself, in one go, once OK is pressed.
  private final PropertyEditorSaveMode.Deferred saveMode = new PropertyEditorSaveMode.Deferred();

  private Stage stage;

  private FilterSection section;

  private FilterSectionSnapshot snapshot;

  private Optional<ButtonType> result = Optional.of(ButtonType.CANCEL);

  @FXML
  private void initialize() {
    labelController.configureCustom("label", "LABEL");
    labelController.setSaveMode(saveMode);
    fieldsController.setSaveMode(saveMode);
  }

  void initDialog(Stage stage, ElementIndex documentModelIndex, @NonNull FilterSection section) {
    this.stage = stage;
    this.section = section;
    this.snapshot = new FilterSectionSnapshot(section);

    idField.setText(section.getId());

    labelController.setCustom(section::getLabel);
    fieldsController.setDocumentModelIndex(documentModelIndex);
    fieldsController.setFields(section::getFields);
  }

  /** Unregisters the embedded panels once this dialog is closed, regardless of how (OK, Cancel or the window's
   * own close button) - see {@link Dialogs#showSection}, which calls this from the stage's {@code onHidden}
   * handler. */
  void destroy() {
    labelController.destroy();
    fieldsController.destroy();
  }

  @Override
  public void onDialogCancel() {
    snapshot.restore();
    stage.close();
  }

  @FXML
  private void onDialogSubmit() {
    ProjectItem projectItem = Studio.getSelectedProjectItem();
    if (projectItem != null) {
      projectItem.save();
      StudioEventManager.getInstance().fireModelSavedEvent(projectItem);
    }
    result = Optional.of(ButtonType.OK);
    stage.close();
  }

  boolean isConfirmed() {
    return result.isPresent() && result.get() == ButtonType.OK;
  }
}
