plugins {
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

javafx {
    version = '21.0.4'
    modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {
    implementation project(':a12-studio-commons')
    implementation 'org.apache.poi:poi:5.3.0'
    implementation 'org.apache.poi:poi-ooxml:5.3.0'
}
