dependencies {
    implementation project(':a12-studio-models')

    testImplementation platform('org.junit:junit-bom:5.11.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'tools.jackson.core:jackson-databind:3.1.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
