name: A12 Studio Build

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ######################################################################################################################
  # Windows Packaging
  ######################################################################################################################
  build:
    name: Packaging
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Install Inno Setup
        run: choco install innosetup --yes

      - name: Checkout A12 Studio
        uses: actions/checkout@v6

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Extract project version
        id: project
        shell: pwsh
        run: |
          $version = (Select-String -Path build.gradle -Pattern "version = '(.*)'").Matches[0].Groups[1].Value
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Build Installer
        run: .\gradlew.bat :a12-studio-ui:buildInstaller

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v7
        with:
          name: A12-Studio-Installer-${{ steps.project.outputs.version }}
          path: |
            ./Output/A12-Studio/A12-Studio-Full-Installer-*.exe
            ./Output/A12-Studio/A12-Studio.exe

      - name: Draft Release
        uses: softprops/action-gh-release@v3
        if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
        with:
          draft: true
          tag_name: ${{ steps.project.outputs.version }}
          files: |
            ./Output/A12-Studio/A12-Studio-Full-Installer-*.exe
            ./Output/A12-Studio/A12-Studio.exe


  ######################################################################################################################
  # Cleanup Old Workflow Runs
  ######################################################################################################################
  cleanup:
    name: Delete Old Workflow Runs
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      actions: write
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 10